### PR TITLE
Adds `NullOrOutOfRange` clauses, adding support for nullable classes/structs to `OutOfRange`

### PR DESCRIPTION
**Pull request by rafaelsc**
- Add `NullOrOutOfRange` to Check for Null or `OutOfRange` for References and Nullable Value Types.
- Add `NullOrOutOfSQLDateRange` to Nullable DateTime.
- Add Missing JetBrains.Annotations and Other Attribute to `OutOfRange` and `NullOrOutOfRange` methods
- Add More Documentation to OutOfRange methods
- Add more Unit Tests
- Bump C# version to 9 - to have better support for nullable in generics.
- Fix Issue #142

### CODE REVIEW

**Review by ardalis — APPROVED** [review]

**Comment by ardalis** [comment]
Can you fix the build?

**Comment by rafaelsc** [comment]
Yes. I just solvedthe Merge Conflicts.

**Comment by ardalis** [comment]
Thanks, can you look at the build failure?

```
Build FAILED.

Error: GuardClauseExtensions.cs(200,143): error CS8627: A nullable type parameter must be known to be a value type or non-nullable reference type. Consider adding a 'class', 'struct', or type constraint. [D:\a\GuardClauses\GuardClauses\src\GuardClauses\GuardClauses.csproj]
Error: GuardClauseExtensions.cs(229,150): error CS8627: A nullable type parameter must be known to be a value type or non-nullable reference type. Consider adding a 'class', 'struct', or type constraint. [D:\a\GuardClauses\GuardClauses\src\GuardClauses\GuardClauses.csproj]
Error: GuardClauseExtensions.cs(229,278): error CS8627: A nullable type parameter must be known to be a value type or non-nullable reference type. Consider adding a 'class', 'struct', or type constraint. [D:\a\GuardClauses\GuardClauses\src\GuardClauses\GuardClauses.csproj]
Error: GuardClauseExtensions.cs(229,338): error CS8627: A nullable type parameter must be known to be a value type or non-nullable reference type. Consider adding a 'class', 'struct', or type constraint. [D:\a\GuardClauses\GuardClauses\src\GuardClauses\GuardClauses.csproj]
Error: GuardClauseExtensions.cs(200,143): error CS8627: A nullable type parameter must be known to be a value type or non-nullable reference type. Consider adding a 'class', 'struct', or type constraint. [D:\a\GuardClauses\GuardClauses\src\GuardClauses\GuardClauses.csproj]
Error: GuardClauseExtensions.cs(229,150): error CS8627: A nullable type parameter must be known to be a value type or non-nullable reference type. Consider adding a 'class', 'struct', or type constraint. [D:\a\GuardClauses\GuardClauses\src\GuardClauses\GuardClauses.csproj]
Error: GuardClauseExtensions.cs(229,278): error CS8627: A nullable type parameter must be known to be a value type or non-nullable reference type. Consider adding a 'class', 'struct', or type constraint. [D:\a\GuardClauses\GuardClauses\src\GuardClauses\GuardClauses.csproj]
Error: GuardClauseExtensions.cs(229,338): error CS8627: A nullable type parameter must be known to be a value type or non-nullable reference type. Consider adding a 'class', 'struct', or type constraint. [D:\a\GuardClauses\GuardClauses\src\GuardClauses\GuardClauses.csproj]
    0 Warning(s)
    8 Error(s)
```

**Comment by rafaelsc** [comment]
C# 9 Solve these errors. And looks like your build system is using on C#8. Open the project in VS will compile normally.

I don't have experience with GitHub action CI/CD. I will make a change to build using Net5 and Change the `global.json` to use Net5 too.

**Comment by ardalis** [comment]
All right, @rafaelsc, sorry to say it but can you re-apply this to the now-split-up files in the solution?

**Comment by ardalis** [comment]
I got rid of the global.json and everything should "just work" now with net6.0, by the way.

**Comment by rafaelsc** [comment]
@ardalis Sorry I only had the opportunity to fix the conflicts this week.
The Build is failing look like by some error in the build pipeline.

**Comment by rafaelsc** [comment]
I will be solving this conflits tomorrow

**Comment by rafaelsc** [comment]
Conflits Solved

**Pull request merged**
