### PR TITLE
Upgrade to dotnet 7.0

### PR DESCRIPTION
**Pull request by amal-stack**

### CODE REVIEW

**Comment by ardalis** [comment]
If we update to net7 that will make it tough for older projects to use. Is there anything that requires net7?

**Comment by amal-stack** [comment]
@ardalis I tried upgrading because I noticed the CI builds have been failing lately due to an error in the [ReferenceAssemblyAnnotator](https://github.com/tunnelvisionlabs/ReferenceAssemblyAnnotator) library:
Build Errors
It is an [open issue](https://github.com/tunnelvisionlabs/ReferenceAssemblyAnnotator/issues/92) in the library that it breaks on projects with multiple framework targets.  
In my fork, the build succeeded when I upgraded to .NET 7. (This might also be due to the fact that `build.yml` uses dotnet 7 to build the project, not quite sure):
Commits
Notice the top two commits where the build started failing when I reverted to .NET 6.

**Comment by ardalis** [comment]
Weird, thanks. Looking into it.

**Comment by ardalis** [comment]
Since we still have netstandard targeting hopefully this should be fine.

**Pull request merged**
