### PR TITLE
Created async overload for clausules that use a predicate

### PR DESCRIPTION
**Pull request by danny-bos-developer**
PR regarding dicussion 226:
https://github.com/ardalis/GuardClauses/discussions/226

I've created the async overloads and UnitTests for it.

### CODE REVIEW

**Comment by danny-bos-developer** [comment]
I made GetCustomStruct public. There was a build error for this.

**Review by Reapism — CHANGES_REQUESTED** [review]
Great job @danny-bos-developer for creating easy to read, and succinct unit tests. This could be a great fail early scenario generally speaking.

Small suggestion... I would rename the method to be called **`ExpressionAsync`** instead of  `AgainstExpressionAsync` since this is extending off the `IGuardClause` of this library, and its only entry point is via the `Against` property so it is already explicit via usage of the library.

Great addition! Cheers.

**Comment by danny-bos-developer** [comment]
I need some TLC for this PR please

**Comment by Reapism** [comment]
@danny-bos-developer are you not able to edit the pull request?

**Comment by danny-bos-tata** [comment]
No I can’t

**Comment by ardalis** [comment]
I'll get it sorted

**Comment by danny-bos-tata** [comment]
Alright, thank you. You probably need to remerge with the master again too because JetBrains has been removed.

Kind regards
Danny

**Comment by ardalis** [comment]
Temporarily breaking main with this...

**Pull request merged**
