### PR TITLE
Add Guard.Against.Default and Tests

### PR DESCRIPTION
**Pull request by KyleMcMaster**
Added functionality requested in issue #36 as well as tests covering the new guard clause extension.
Any suggestions for improvement are greatly appreciated. 

Thanks!
-KM

### CODE REVIEW

**Comment by terryjbutler** [comment]
This looks good! 

Food for thought perhaps, but I have been wondering about Nullable types. 

For example, the default keyword used on a Guid? will return null but the default for the underlying Guid type is '00000000-0000-0000-0000-000000000000' and as a result Nullable types passed in won't be caught in this manner.

I have wanted to succinctly catch both null and empty nullable Guids in development already using this library. What does everyone else think?

**Comment by KyleMcMaster** [comment]
@terryjbutler I could see it being useful to implement a `Guard.Against.NullOrDefault` as part of the core extensions. I use a Guard like 

```
        public static void NullOrDefault<T>(this IGuardClause guardClause, T input, string parameterName)
        {
            if (typeOfT.IsValueType && EqualityComparer<T>.Default.Equals(input, default))
            {
                throw new ArgumentException($"Parameter [{parameterName}] is default value for type {typeof(T).Name}");
            }

            if (!typeOfT.IsValueType && input == null)
            {
                throw new ArgumentNullException(parameterName, $"Parameter [{parameterName}] of type {typeof(T).Name} is null");
            }
        }

```

**Comment by KyleMcMaster** [comment]
@terryjbutler I would be interested in adding something like that to the existing extension `NullOrEmpty` if that is what you were thinking.

Thoughts on the following?
```
       public static void NullOrEmpty(this IGuardClause guardClause, object input, string parameterName)
        {
            Guard.Against.Null(input, parameterName);

            if (input is string && (string)input == string.Empty) 
            {
                throw new ArgumentException($"Required input {parameterName} was empty.", parameterName);
            }
            else if (input is Guid? && (Guid?)input == Guid.Empty)
            {
                throw new ArgumentException($"Required input {parameterName} was empty.", parameterName);
            }
        }
```

**Comment by terryjbutler** [comment]
I'm wondering if it might be a good idea to reduce the if statements (just to avoid ambiguity) and perhaps have explicit Guid/etc checks. I think that it would also help the clarity when quickly viewing the thrown exceptions in the guard? 

I'd also worry that if a type which wasn't present in the if statement might produce false negatives and proceed happily when it is indeed logically "empty". 

I'm not 100% sure on the best solution, I'll have a good think about it when I can grab some time. 

What do you think @ardalis ?

**Comment by ardalis** [comment]
I don't see a problem with adding this as-is.

For the problem of Guid? for example where you want to avoid null and Guid.Empty I think we could have a separate Guard clause (in a separate PR) for that. We already have NullOrEmpty for string so adding it for Guid should be fine, in a strongly typed manner rather than taking an `object` input.

**Pull request merged**
