### PR TITLE
Adding netstandard2.0 as a target

### PR DESCRIPTION
**Pull request by kjjuno**
Currently we have to accept several extra dependencies into our netcoreapp3.0 project in order to reference these. Adding this build target should eliminate that.

### CODE REVIEW

**Comment by ardalis** [comment]
Hmm, for some reason I thought it was best to target the lowest netstandard that you could support, as that was to provide the widest reach for potential consumers. I didn't think there was a scenario where it made sense to target multiple netstandard versions.

**Comment by kjjuno** [comment]
I could be misinterpreting what was happening to us. There are some other libs that you reference, and maybe that was what was coming in. Let me dig a bit more and get back to you.

**Comment by kjjuno** [comment]
We ended up forking and modifying for our needs. So, unless you have a reason to take this PR I would probably just close this

**Comment by ardalis** [comment]
I’m curious if there’s anything you changed that would help others...

**Comment by kjjuno** [comment]
I stripped out all dependencies. So, no telerik NotNullAttribute stuff. I removed all build targets and replaced them with only netstandard2.0. And I changed the namespace for our company.

**Pull request closed without merging**
