### PR TITLE
Extendable guards

### PR DESCRIPTION
**Pull request by dvanherten**
This is the PR as is it was referenced in #2 

If you'd like me to clean anything up first let me know and I can make the changes. If it's easier to just change a few names or shift things around after, that works too. :)

First real PR. Not sure on etiquette. ha!

### CODE REVIEW

**Comment by dvanherten** [comment]
I did end up cleaning it up a bit. 

I added the xml comments you had to both ways the existing guards could now be called. 

I renamed a couple tests to better explain intent between shortcut (right on Guard) vs extension method (through the Against property)

I left the Guard.cs class all one class even though there is two classes and an interface. Originally all one because I felt it was easier to understand the changes I was trying to make. Left it that way as I wasn't sure what your preference would be and wasn't an overly large file at this point.

**Comment by jpreese** [comment]
To add to this, I think Guard be a Singleton. I don't think it makes much sense for consumers to ever new up `Guard` and we shouldn't need to create a new one everytime we want to validate a clause.

**Comment by dvanherten** [comment]
Very true that it goes against the intent of the guard to new it up. I did basically intend it that way, heck, _Against_ is basically a renamed _Instance_ property that you normally see in a singleton. 

So I added the private constructor.

**Comment by jpreese** [comment]
Yep, agreed. That's how I viewed this anyway. Though to fully implement Singleton, you'll want to check if `Against` has been initialized and if so just return itself, otherwise new up a `Guard` instance. 

Right now you're newing up `Guard` every call to `Against`

**Comment by dvanherten** [comment]
I don't believe that is the case. It is using a syntactic sugar property initializer on the get only property.
Essentially there should not be a case where Against isn't initialized and initialized just the one time.

{ get; } = new Guard();

Were you thinking it was this?

{ get { return new Guard(); }

Or am I missing something?

**Comment by jpreese** [comment]
I guess my main concern was for multithreaded environments. If it's not something we care about, then it works out. Using an autoprop we don't have that control (unless the constructor was static). 

I don't necessarily want to overcomplicate the solution, but food for thought. This is looking great!

**Comment by dvanherten** [comment]
Thanks! 

If there is a multi-threading concern that is not being handled, it would likely be fair to want to address it. For now, I think i'll wait for Steve to chime in before we go down any one path too far. Handle the rest through iteration of new issues feels like the right call to me.

Really appreciate the feedback though!

**Comment by ardalis** [comment]
Thanks for the great conversation! I've been swamped but will try to look at this and get it merged today.

**Comment by ardalis** [comment]
Thanks!

**Pull request merged**
