### PR TITLE
NullOrEmpty clauses were not respecting null inputs

### PR DESCRIPTION
**Pull request by taylorc**
NullOrEmpty clauses were not respected null input or documentation that the clause can throw an ArgumentNullException.

### CODE REVIEW

**Comment by ardalis** [comment]
Doesn't the current behavior, which relies on `Guard.Against.Null()` already throw a NullReferenceException in the case of null, and an ArgumentException otherwise? Is that what you're trying to change? I think if it's null, then the NRE is the appropriate exception to throw. Also this would break lots of tests that are expecting the current behavior.

**Comment by fiseni** [comment]
I do believe you were thinking of `ArgumentNullException` but typed `NullReferenceException` :) The NRE is the default language behavior anyway. Writing just to avoid further confusion in the thread.

As for the PR, it's already guarded for null. Is there anything we're missing out?

**Comment by ardalis** [comment]
You're right, I meant ArgumentNullException. I'm not sure this is anything we need - was hoping @taylorc would respond with the problem he's looking to fix.

**Comment by ardalis** [comment]
Closing for now; if we're missing something about what you need let us know.

**Pull request closed without merging**
